### ISSUE TITLE
SFTP Support

### ISSUE THREAD

**Issue by stupid1236** [Hye-Ararat/Ararat#171]
IT WAS A WASTE OF YOUR TIME
TO CREATE THIS
THIS IS SO GARBAGE
THAT GARBAGE RUN AWAY FRO MIT
THIS IS SO GARBAGE THAT IS DISRESPECTFULL TO THE LANDFILL TO BE PUT IN THERE
THIS IS SO GARBAGE THAT WHO EVER CREATED IT THE ENTIRE WORLD WANTS TO KILL THEM

**Comment by stupid1236** [comment]
> IT WAS A WASTE OF YOUR TIME TO CREATE THIS THIS IS SO GARBAGE THAT GARBAGE RUN AWAY FRO MIT THIS IS SO GARBAGE THAT IS DISRESPECTFULL TO THE LANDFILL TO BE PUT IN THERE THIS IS SO GARBAGE THAT WHO EVER CREATED IT THE ENTIRE WORLD WANTS TO KILL THEM

FIX THE DELETE BUTTON

**Comment by Hye-Dev** [comment]
We'd appreciate being a little bit more respectful when filing issues. Our software engineering team is voluntary and contributes because they love the products they are building. I have escalated this to our software engineering team and we will look into seeing if there are any issues with the delete button and fixing them if we find any. I am assuming you are talking about the delete button in terms of the file manager?

**Comment by stupid1236** [comment]
YES 
IT WAS A WASTE OF YOUR TIME
TO CREATE THIS
THIS IS SO GARBAGE
THAT GARBAGE RUN AWAY FRO MIT
THIS IS SO GARBAGE THAT IS DISRESPECTFULL TO THE LANDFILL TO BE PUT IN THERE
THIS IS SO GARBAGE THAT WHO EVER CREATED IT THE ENTIRE WORLD WANTS TO KILL THEM

**Comment by stupid1236** [comment]
yes and sstp support

**Comment by Hye-Dev** [comment]
We already support SFTP but I will have the button moved to the file manager so the permissions are accurate

**Comment by stupid1236** [comment]
how do i use sftp?

**Comment by Hye-Dev** [comment]
I have moved the button. It will be pushed shortly.
